# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ccg/simple

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ccg/simple

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ccg/simple/CMakeFiles /home/ccg/simple/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ccg/simple/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named simplelang

# Build rule for target.
simplelang: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplelang
.PHONY : simplelang

# fast build rule for target.
simplelang/fast:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/build
.PHONY : simplelang/fast

#=============================================================================
# Target rules for targets named sl2R

# Build rule for target.
sl2R: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sl2R
.PHONY : sl2R

# fast build rule for target.
sl2R/fast:
	$(MAKE) -f CMakeFiles/sl2R.dir/build.make CMakeFiles/sl2R.dir/build
.PHONY : sl2R/fast

sl2R.o: sl2R.cpp.o
.PHONY : sl2R.o

# target to build an object file
sl2R.cpp.o:
	$(MAKE) -f CMakeFiles/sl2R.dir/build.make CMakeFiles/sl2R.dir/sl2R.cpp.o
.PHONY : sl2R.cpp.o

sl2R.i: sl2R.cpp.i
.PHONY : sl2R.i

# target to preprocess a source file
sl2R.cpp.i:
	$(MAKE) -f CMakeFiles/sl2R.dir/build.make CMakeFiles/sl2R.dir/sl2R.cpp.i
.PHONY : sl2R.cpp.i

sl2R.s: sl2R.cpp.s
.PHONY : sl2R.s

# target to generate assembly for a file
sl2R.cpp.s:
	$(MAKE) -f CMakeFiles/sl2R.dir/build.make CMakeFiles/sl2R.dir/sl2R.cpp.s
.PHONY : sl2R.cpp.s

sl_code.o: sl_code.cpp.o
.PHONY : sl_code.o

# target to build an object file
sl_code.cpp.o:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_code.cpp.o
.PHONY : sl_code.cpp.o

sl_code.i: sl_code.cpp.i
.PHONY : sl_code.i

# target to preprocess a source file
sl_code.cpp.i:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_code.cpp.i
.PHONY : sl_code.cpp.i

sl_code.s: sl_code.cpp.s
.PHONY : sl_code.s

# target to generate assembly for a file
sl_code.cpp.s:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_code.cpp.s
.PHONY : sl_code.cpp.s

sl_host.o: sl_host.cpp.o
.PHONY : sl_host.o

# target to build an object file
sl_host.cpp.o:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_host.cpp.o
.PHONY : sl_host.cpp.o

sl_host.i: sl_host.cpp.i
.PHONY : sl_host.i

# target to preprocess a source file
sl_host.cpp.i:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_host.cpp.i
.PHONY : sl_host.cpp.i

sl_host.s: sl_host.cpp.s
.PHONY : sl_host.s

# target to generate assembly for a file
sl_host.cpp.s:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_host.cpp.s
.PHONY : sl_host.cpp.s

sl_misc.o: sl_misc.cpp.o
.PHONY : sl_misc.o

# target to build an object file
sl_misc.cpp.o:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_misc.cpp.o
.PHONY : sl_misc.cpp.o

sl_misc.i: sl_misc.cpp.i
.PHONY : sl_misc.i

# target to preprocess a source file
sl_misc.cpp.i:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_misc.cpp.i
.PHONY : sl_misc.cpp.i

sl_misc.s: sl_misc.cpp.s
.PHONY : sl_misc.s

# target to generate assembly for a file
sl_misc.cpp.s:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_misc.cpp.s
.PHONY : sl_misc.cpp.s

sl_pars.o: sl_pars.cpp.o
.PHONY : sl_pars.o

# target to build an object file
sl_pars.cpp.o:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_pars.cpp.o
.PHONY : sl_pars.cpp.o

sl_pars.i: sl_pars.cpp.i
.PHONY : sl_pars.i

# target to preprocess a source file
sl_pars.cpp.i:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_pars.cpp.i
.PHONY : sl_pars.cpp.i

sl_pars.s: sl_pars.cpp.s
.PHONY : sl_pars.s

# target to generate assembly for a file
sl_pars.cpp.s:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_pars.cpp.s
.PHONY : sl_pars.cpp.s

sl_tbl.o: sl_tbl.cpp.o
.PHONY : sl_tbl.o

# target to build an object file
sl_tbl.cpp.o:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_tbl.cpp.o
.PHONY : sl_tbl.cpp.o

sl_tbl.i: sl_tbl.cpp.i
.PHONY : sl_tbl.i

# target to preprocess a source file
sl_tbl.cpp.i:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_tbl.cpp.i
.PHONY : sl_tbl.cpp.i

sl_tbl.s: sl_tbl.cpp.s
.PHONY : sl_tbl.s

# target to generate assembly for a file
sl_tbl.cpp.s:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_tbl.cpp.s
.PHONY : sl_tbl.cpp.s

sl_tkn.o: sl_tkn.cpp.o
.PHONY : sl_tkn.o

# target to build an object file
sl_tkn.cpp.o:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_tkn.cpp.o
.PHONY : sl_tkn.cpp.o

sl_tkn.i: sl_tkn.cpp.i
.PHONY : sl_tkn.i

# target to preprocess a source file
sl_tkn.cpp.i:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_tkn.cpp.i
.PHONY : sl_tkn.cpp.i

sl_tkn.s: sl_tkn.cpp.s
.PHONY : sl_tkn.s

# target to generate assembly for a file
sl_tkn.cpp.s:
	$(MAKE) -f CMakeFiles/simplelang.dir/build.make CMakeFiles/simplelang.dir/sl_tkn.cpp.s
.PHONY : sl_tkn.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... simple"
	@echo "... simplelang"
	@echo "... sl2R"
	@echo "... sl2R.o"
	@echo "... sl2R.i"
	@echo "... sl2R.s"
	@echo "... sl_code.o"
	@echo "... sl_code.i"
	@echo "... sl_code.s"
	@echo "... sl_host.o"
	@echo "... sl_host.i"
	@echo "... sl_host.s"
	@echo "... sl_misc.o"
	@echo "... sl_misc.i"
	@echo "... sl_misc.s"
	@echo "... sl_pars.o"
	@echo "... sl_pars.i"
	@echo "... sl_pars.s"
	@echo "... sl_tbl.o"
	@echo "... sl_tbl.i"
	@echo "... sl_tbl.s"
	@echo "... sl_tkn.o"
	@echo "... sl_tkn.i"
	@echo "... sl_tkn.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

